language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: gh-deployment-app # see README
  api_key:
    secure: nVORfit167bkmze7lhusidrN8ksP8huvHrjV6KUNqhhzdTKWsKkZ4aBdjoun6eECYhMAYh6nZN5tMSsxBe80aTqqjoGeso9MXbNIAr7g1UfOFtiLObK/Pbqn/J4G6ZyKFNuJQA3mEh0ZCT12MpwNjwO9zNtW6YYm43clvFzBl1y87dwMflvYzRzbDIxAUuGs5VB03vUUigRiUqvhrwr9TRTqVpPcdyDcWEjHNbpxCEf/n0oMYv2RrYUytnFgCs+jkcEo/qKViu7BGGBwrMQaEg+ZTdaK1ulGfXVFOgEXfKVQ1hpz2IaCX9/D6RB/kIfDbBqF/eZhdq9nC/bTodR/haVvt9mfPwBzjKdW61ao7kgM2cjqLgtIi67EpJRAUjnbb7nf/AVBsD2U7/oLQ0y9PfueDzCdsxyD1JsRINsbIyTIcdgOZMGr0ZiJgs543tMaXIx9yp0UfzM0tsL0wode1EuHm1K4yvgEO7R4V02onMLHE+SVcWfq6gcdaUY3EhTjNAflhMD/o8kVi2KfzsLr17ZH/EAHkaoh6Zu5B59kXs/oItMDcFFNxWTgqyfl1IRkFB8UtvTFCfwVrF9PXqHielwXFsq+Z5Tazl+hOb/wjkkSF43j+5uyBjLsxBgPcPY0nz9/Wt0UPK3vxkNexN+gf25uljEEBqqQ+PBLdlM/bBg=
